"""add image_url to detection_histories

Revision ID: 494284da7838
Revises: b1c2d3e4f5a6
Create Date: 2026-06-04 21:28:38.203759

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '494284da7838'
down_revision = 'b1c2d3e4f5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction_logs')
    with op.batch_alter_table('detection_histories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_histories', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    op.create_table('prediction_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('predicted_class', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('plant_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('disease_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_healthy', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('prediction_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('prediction_logs_pkey'))
    )
    # ### end Alembic commands ###
